domain: dev.devium.net
collab_domain: "collab.{{ domain }}"
auth_domain: "auth.{{ domain }}"
matrix_domain: "matrix.{{ domain }}"
element_domain: "element.{{ domain }}"
jitsi_domain: "jitsi.{{ domain }}"
www_domain: "www.{{ domain }}"
s3_bucket_name: devium-kink-dev

bastion_host: "bastion.{{ domain }}"
collab_host: 192.168.1.185
db_host: terraform-20210719210349773800000001.ccoagnqigki8.eu-central-1.rds.amazonaws.com
auth_host: 192.168.1.66
matrix_host: 192.168.1.11
