---
# Adds user groups to the userinfo and token endpoints. Used for example by NextCloud.

- name: Add groups mapper to profile client scope
  community.general.keycloak_clientscope:
    auth_realm: master
    auth_username: admin
    auth_password: "{{ keycloak_password }}"
    auth_keycloak_url: "https://{{ auth_domain }}/auth"
    realm: "{{ keycloak_realm }}"
    name: profile
    protocol_mappers:
      - config:
          access.token.claim: "true"
          claim.name: "groups"
          full.path: "false"
          id.token.claim: "true"
          userinfo.token.claim: "true"
        name: "groups"
        protocol: "openid-connect"
        protocolMapper: "oidc-group-membership-mapper"
