# Allow users to delete their own account by enabling delete-account as default role for the account client.
- name: Get account client roles
  uri:
    url: "{{ keycloak_realm_api_base }}/clients/{{ (clients | json_query(query))[0] }}/roles"
    method: GET
    headers: "{{ keycloak_api_headers }}"
  register: account_roles
  vars:
    query: "json[?clientId=='account'].id"

- name: Get realm default roles
  uri:
    url: "{{ keycloak_realm_api_base }}/roles-by-id/{{ realm.json.defaultRole.id }}/composites"
    method: GET
    headers: "{{ keycloak_api_headers }}"
  register: default_roles

- name: Add delete-account to default roles
  uri:
    url: "{{ keycloak_realm_api_base }}/roles-by-id/{{ realm.json.defaultRole.id }}/composites"
    method: POST
    headers: "{{ keycloak_api_headers }}"
    body_format: json
    body: [{ "id": "{{ (account_roles | json_query(query))[0] }}" }]
    status_code: [204]
  changed_when: true
  vars:
    query: "json[?name=='delete-account'].id"
  when: "'delete-account' not in default_roles.json | string"

- name: Get delete_account required action
  uri:
    url: "{{ keycloak_realm_api_base }}/authentication/required-actions/delete_account"
    method: GET
    headers: "{{ keycloak_api_headers }}"
  register: delete_account_action

- name: Enable delete-account required action
  uri:
    url: "{{ keycloak_realm_api_base }}/authentication/required-actions/delete_account"
    method: PUT
    headers: "{{ keycloak_api_headers }}"
    body_format: json
    body: |
      {
        "alias": "delete_account",
        "name": "Delete Account",
        "providerId": "delete_account",
        "enabled": true,
        "defaultAction": false,
        "priority": 60,
        "config": {}
      }
    status_code: [204]
  changed_when: true
  when: "not delete_account_action.json.enabled"
