---
- name: Get API access token
  uri:
    url: https://{{ auth_domain }}/auth/realms/master/protocol/openid-connect/token
    method: POST
    body_format: form-urlencoded
    body:
      client_id: admin-cli
      username: admin
      grant_type: password
      password: "{{ keycloak_password }}"
  register: access_token

- name: Increase access token lifespan
  community.general.keycloak_realm:
    auth_realm: master
    auth_username: admin
    auth_password: "{{ keycloak_password }}"
    auth_keycloak_url: "https://{{ auth_domain }}/auth"
    realm: "master"
    access_token_lifespan: 300
  when: access_token.json.expires_in < 300

- name: Get new, longer-lasting API access token
  uri:
    url: https://{{ auth_domain }}/auth/realms/master/protocol/openid-connect/token
    method: POST
    body_format: form-urlencoded
    body:
      client_id: admin-cli
      username: admin
      grant_type: password
      password: "{{ keycloak_password }}"
  register: access_token
  when: access_token.json.expires_in < 300
