---
- import_tasks: "{{ role_path }}/tasks/setup_keycloak.yml"
  tags: 
    - setup-all
    - setup-keycloak

- import_tasks: "{{ role_path }}/tasks/start_keycloak.yml"
  tags: 
    - start
    - start-keycloak

- import_tasks: "{{ role_path }}/tasks/init_realm.yml"
  tags: 
    - init-all
    - init-keycloak
    - init-keycloak-realm

- import_tasks: "{{ role_path }}/tasks/init_access_token.yml"
  tags: 
    - init-all
    - init-keycloak
    - init-keycloak-authentication
    - init-keycloak-google
    - init-keycloak-delete-account

- import_tasks: "{{ role_path }}/tasks/get_state.yml"
  tags: 
    - init-all
    - init-keycloak
    - init-keycloak-authentication
    - init-keycloak-delete-account

- import_tasks: "{{ role_path }}/tasks/init_delete_account.yml"
  tags: 
    - init-all
    - init-keycloak
    - init-keycloak-delete-account

- import_tasks: "{{ role_path }}/tasks/init_hedgedoc_mapping.yml"
  tags: 
    - init-all
    - init-keycloak

- import_tasks: "{{ role_path }}/tasks/init_google_provider.yml"
  tags: 
    - init-all
    - init-keycloak
    - init-keycloak-google

- import_tasks: "{{ role_path }}/tasks/init_authentication.yml"
  tags: 
    - init-all
    - init-keycloak
    - init-keycloak-authentication
