- name: Create Keycloak dir
  file:
    path: "{{ home }}/keycloak/config/nginx/site-confs"
    state: directory

- name: Copy docker-compose.yml to target machine
  template:
    src: docker-compose.yml.j2
    dest: "{{ home }}/keycloak/docker-compose.yml"

- name: Copy SWAG reverse proxy config for Keycloak
  template:
    src: keycloak.conf.j2
    dest: "{{ home }}/keycloak/config/nginx/site-confs/keycloak.conf"

- name: Copy custom theme
  copy:
    src: custom/
    dest: "{{ home }}/keycloak/custom/"

- name: Create tranlsation dirs
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ home }}/keycloak/custom/login/messages"
    - "{{ home }}/keycloak/custom/account/messages"

- name: Download login translations
  get_url:
    url: "{{ keycloak_translations_login_url }}/messages_{{ item }}.properties"
    dest: "{{ home }}/keycloak/custom/login/messages"
  with_items: "{{ keycloak_locales_download }}"

- name: Download account translations
  get_url:
    url: "{{ keycloak_translations_account_url }}/messages_{{ item }}.properties"
    dest: "{{ home }}/keycloak/custom/account/messages"
  with_items: "{{ keycloak_locales_download }}"
