---
- name: Stop Keycloak and reverse proxy
  docker_compose:
    project_src: "{{ home }}/keycloak"
    state: absent
  become: yes
  tags:
    - stop-keycloak

- name: Start Keycloak and reverse proxy
  docker_compose:
    project_src: "{{ home }}/keycloak"
    state: present
  become: yes

- name: Wait for startup
  wait_for:
    timeout: 60
  tags:
    - wait-for-startup
