- name: Apply terraform project
  community.general.terraform:
    project_path: "{{ role_path }}/files"
    workspace: "{{ terraform_config_workspace }}"
    variables: "{{ terraform_config_variables }}"
    state: present
    plan_file: "{{ terraform_config_plan_file }}"
  register: terraform_result

- name: Print Terraform output
  debug:
    msg: "{{ terraform_result.stdout }}"

# TODO: Include this in the terraform project once possible
- name: Set realm's browser flow and default client scopes
  community.general.keycloak_realm:
    auth_keycloak_url: "https://{{ terraform_config_subdomains.keycloak }}.{{ terraform_config_domain }}/auth"
    auth_realm: master
    auth_username: admin
    auth_password: "{{ terraform_config_admin_passwords.keycloak }}"
    realm: "{{ terraform_config_keycloak_realm }}"
    # https://github.com/mrparkers/terraform-provider-keycloak/issues/298
    browser_flow: browser-custom
