---
- name: Get app config
  community.docker.docker_container_exec:
    container: nextcloud
    user: "www-data"
    command: "php occ config:list"
  register: app_config_tmp
  become: yes
  changed_when: false

- name: Install apps
  community.docker.docker_container_exec:
    container: nextcloud
    user: "www-data"
    command: "php occ app:install {{ item }}"
  become: yes
  changed_when: true
  when: (app_config_tmp.stdout | from_json).apps[item] is not defined
  with_items:
    - calendar
    - sociallogin

- name: Get app config again
  community.docker.docker_container_exec:
    container: nextcloud
    user: "www-data"
    command: "php occ config:list"
  register: app_config
  become: yes
  changed_when: false

- name: Enable apps
  community.docker.docker_container_exec:
    container: nextcloud
    user: "www-data"
    command: "php occ app:enable {{ item }}"
  become: yes
  changed_when: true
  when: (app_config.stdout | from_json).apps[item].enabled == "no"
  with_items:
    - calendar
    - logreader
    - sociallogin

- name: Disable apps
  community.docker.docker_container_exec:
    container: nextcloud
    user: "www-data"
    command: "php occ app:disable {{ item }}"
  become: yes
  changed_when: true
  when: (app_config.stdout | from_json).apps[item].enabled == "yes"
  with_items:
    - accessibility
    - activity
    - circles
    - comments
    - contactsinteraction
    - dashboard
    - federation
    - files_pdfviewer
    - files_rightclick
    - files_sharing
    - files_trashbin
    - files_versions
    - files_videoplayer
    - firstrunwizard
    - nextcloud_announcements
    - notifications
    - password_policy
    - photos
    - privacy
    - recommendations
    - serverinfo
    - sharebymail
    - support
    - survey_client
    - systemtags
    - text
    - theming
    - updatenotification
    - user_status
    - weather_status
