---
- name: Create NextCloud dirs
  file:
    path: "{{ home }}/nextcloud/config/nginx/site-confs"
    state: directory

- name: Copy docker-compose.yml to target machine
  template:
    src: docker-compose.yml.j2
    dest: "{{ home }}/nextcloud/docker-compose.yml"

- name: Copy SWAG reverse proxy config for NextCloud
  template:
    src: nextcloud.conf.j2
    dest: "{{ home }}/nextcloud/config/nginx/site-confs/nextcloud.conf"
