- name: Ensure all secrets have been generated
  lineinfile:
    path: "{{ secrets_file }}"
    search_string: <generate>
    state: absent
  check_mode: yes
  register: secrets_check
  tags:
    - always

- name: Fail when there are still secrets to be generated
  assert:
    that: not secrets_check.changed
    msg: "Some secrets still need to be generated. Run generate-secrets.sh or enter them manually."
  tags:
    - always
