terraform_servers_domain:
terraform_servers_hcloud_token:
terraform_servers_hdns_token:
terraform_servers_hdns_zone_id:
terraform_servers_ssh_key:
terraform_servers_subdomains_override:

terraform_servers_inventory_file: "{{ ansible_inventory_sources[0] }}"
terraform_servers_plan_file: "{{ role_path }}/files/terraform.tfstate.d/{{ terraform_servers_workspace }}/tfplan"
terraform_servers_subdomains: "{{ terraform_servers_subdomains_default | combine(terraform_servers_subdomains_override, recursive=True) }}"
terraform_servers_workspace: default

terraform_servers_subdomains_default:
  collabora: office.next
  element: element
  grafana: grafana
  hedgedoc: doc
  home: www
  jitsi: jitsi
  jitsi_keycloak: auth.jitsi
  keycloak: auth
  nextcloud: next
  pretix: tickets
  shlink: shlink
  synapse: matrix
  workadventure_back: api.play
  workadventure_front: play
  workadventure_maps: maps.play
  workadventure_pusher: pusher.play
  workadventure_uploader: uploader.play

terraform_servers_variables:
  inventory_file: "{{ terraform_servers_inventory_file }}"
  hcloud_token: "{{ terraform_servers_hcloud_token }}"
  hdns_token: "{{ terraform_servers_hdns_token }}"
  hdns_zone_id: "{{ terraform_servers_hdns_zone_id }}"
  ssh_keys: "{{ [terraform_servers_ssh_key] | to_json }}"
  domain: "{{ terraform_servers_domain }}"
  subdomains: "{{ terraform_servers_subdomains | to_json }}"
