terraform_servers_workspace: default

terraform_servers_hcloud_token:
terraform_servers_hdns_token:
terraform_servers_hdns_zone_id:
terraform_servers_domain:
terraform_cluster_subdomains:
  jitsi: jitsi
  keycloak: keycloak
terraform_servers_ssh_key:

terraform_servers_inventory_file: "{{ ansible_inventory_sources[0] }}"
terraform_servers_plan_file: "{{ role_path }}/files/terraform.tfstate.d/{{ terraform_servers_workspace }}/tfplan"

terraform_servers_variables:
  inventory_file: "{{ terraform_servers_inventory_file }}"
  hcloud_token: "{{ terraform_servers_hcloud_token }}"
  hdns_token: "{{ terraform_servers_hdns_token }}"
  hdns_zone_id: "{{ terraform_servers_hdns_zone_id }}"
  ssh_keys: "{{ [terraform_servers_ssh_key] | to_json }}"
  domain: "{{ terraform_servers_domain }}"
  subdomains: "{{ terraform_servers_subdomains | to_json }}"
