terraform_servers_domain:
terraform_servers_hcloud_token:
terraform_servers_hdns_token:
terraform_servers_hdns_zone_id:
terraform_servers_nodes:
terraform_servers_ssh_key:
terraform_servers_stage:

terraform_servers_backend:
  hostname:
  organization:
  token:

terraform_servers_dkim_file: "{{ terraform_servers_secrets_dir }}/mail.{{ terraform_servers_stage }}.txt"
terraform_servers_dkim_file_vault: "{{ terraform_servers_vault_dir }}/mail.{{ terraform_servers_stage }}.txt"
terraform_servers_inventory_file: "{{ ansible_inventory_sources[0] }}"
terraform_servers_plan_file: "{{ role_path }}/files/terraform.tfstate.d/{{ terraform_servers_workspace }}/tfplan"
terraform_servers_secrets_dir: "{{ playbook_dir }}/secrets"
terraform_servers_vault_dir: "{{ playbook_dir }}/vault"
terraform_servers_workspace: "servers-{{ terraform_servers_stage }}"

terraform_servers_subdomains:
  mailserver:

terraform_servers_variables:
  dkim_file: "{{ terraform_servers_dkim_file }}"
  inventory_file: "{{ terraform_servers_inventory_file }}"
  hcloud_token: "{{ terraform_servers_hcloud_token }}"
  hdns_token: "{{ terraform_servers_hdns_token }}"
  hdns_zone_id: "{{ terraform_servers_hdns_zone_id }}"
  nodes: "{{ terraform_servers_nodes | to_json }}"
  ssh_keys: "{{ [terraform_servers_ssh_key] | to_json }}"
  domain: "{{ terraform_servers_domain }}"
  subdomains: "{{ terraform_servers_subdomains | to_json }}"
