- hosts: localhost
  roles:
    - role: terraform
      vars:
        terraform_backend: "{{ terraform_backend_cloud }}"
        terraform_stage: "{{ stage }}"
        terraform_project_path: "{{ playbook_dir }}/terraform/config"
        terraform_workspace_base: config

        terraform_variables:
          app_config: "{{ app_config }}"
          domain: "{{ domain }}"

- hosts: localhost
  roles:
    - role: config
      vars:
        config_app_config: "{{ app_config }}"
        config_domain: "{{ domain }}"
        config_kubeconf_file: "{{ kubeconf_file }}"
        config_release_name: "{{ helm_release_name }}"
