roles:
  - name: mrlesmithjr.netplan
    version: v0.3.0
  - name: lablabs.rke2
    version: 1.14.3

collections:
  - name: community.general
    version: 5.6.0
  - name: kubernetes.core
    version: 2.3.2
