roles:
  - name: mrlesmithjr.netplan
    version: v0.3.0
  - name: lablabs.rke2
    version: 1.7.0

collections:
  - name: community.general
    version: 4.4.0
  - name: kubernetes.core
    version: 2.2.2
