roles:
  - name: mrlesmithjr.netplan
    version: v0.3.0
  - name: lablabs.rke2
    version: 1.9.1

collections:
  - name: community.general
    version: 4.8.0
  - name: kubernetes.core
    version: 2.2.2
