roles:
  - name: mrlesmithjr.netplan
    version: v0.3.0
  - name: lablabs.rke2
    version: 1.17.1

collections:
  - name: community.general
    version: 7.2.0
  - name: kubernetes.core
    version: 2.3.2
