- import_playbook: webservers.yml

- hosts: all
  roles:
    - role: update
      tags: 
        - update

- hosts: master
  roles:
    - role: mrlesmithjr.netplan

- hosts: all
  roles:
    - role: lablabs.rke2
      tags:
        - setup-kubernetes
