terraform_stage:
terraform_plan_file: "{{ terraform_project_path }}/{{ terraform_workspace }}.tfplan"
terraform_project_path:
terraform_targets: []
terraform_variables:
terraform_variables_file: "{{ terraform_project_path }}/{{ terraform_workspace }}.tfvars.json"
terraform_vault_files: []
terraform_vault_files_decryption_path: "{{ terraform_project_path }}/.vault_decrypted/"
terraform_workspace: "{{ terraform_workspace_base }}-{{ terraform_stage }}"
terraform_workspace_base: 

terraform_backend:
  bucket:
  region:
  access_key:
  secret_key:
  dynamodb_table:

terraform_env:
  AWS_ACCESS_KEY_ID: "{{ terraform_backend.access_key }}"
  AWS_SECRET_ACCESS_KEY: "{{ terraform_backend.secret_key }}"

terraform_task_parameters:
  force_init: yes
  init_reconfigure: yes
  plan_file: "{{ terraform_plan_file }}"
  project_path: "{{ terraform_project_path }}"
  provider_upgrade: yes
  targets: "{{ terraform_targets }}"
  variables_file: "{{ terraform_variables_file }}"

  backend_config:
    bucket: "{{ terraform_backend.bucket }}"
    region: "{{ terraform_backend.region }}"
    key: "{{ terraform_workspace }}.tfstate"
    dynamodb_table: "{{ terraform_backend.dynamodb_table }}"
