---
- name: Install requirements for psycopg2
  package:
    name:
      - python-pip
    state: present
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python2

- name: Install psycopg2 for Postgres access
  pip:
    name: psycopg2-binary

- name: Create HedgeDoc database
  postgresql_db:
    login_host: "{{ db_host }}"
    login_password: "{{ db_root_password }}"
    name: "{{ db_hedgedoc_database }}"

- name: Create HedgeDoc database user
  postgresql_user:
    login_host: "{{ db_host }}"
    login_password: "{{ db_root_password }}"
    db: "{{ db_hedgedoc_database }}"
    name: "{{ db_hedgedoc_username }}"
    password: "{{ db_hedgedoc_password }}"
    priv: "ALL"
    no_password_changes: yes
  no_log: true

- name: Create Keycloak database
  postgresql_db:
    login_host: "{{ db_host }}"
    login_password: "{{ db_root_password }}"
    name: "{{ db_keycloak_database }}"

- name: Create Keycloak database user
  postgresql_user:
    login_host: "{{ db_host }}"
    login_password: "{{ db_root_password }}"
    db: "{{ db_keycloak_database }}"
    name: "{{ db_keycloak_username }}"
    password: "{{ db_keycloak_password }}"
    priv: "ALL"
    no_password_changes: yes
  no_log: true

- name: Create matrix database
  postgresql_db:
    login_host: "{{ db_host }}"
    login_password: "{{ db_root_password }}"
    name: "{{ db_matrix_database }}"
    lc_collate: "C"
    lc_ctype: "C"
    template: "template0"

- name: Create matrix database user
  postgresql_user:
    login_host: "{{ db_host }}"
    login_password: "{{ db_root_password }}"
    db: "{{ db_matrix_database }}"
    name: "{{ db_matrix_username }}"
    password: "{{ db_matrix_password }}"
    priv: "ALL"
    no_password_changes: yes
  no_log: true
