---
- name: Create ssh config file
  copy:
    content: ""
    dest: ~/.ssh/config
    force: no
    mode: 0600

- name: Create ssh config entries for other EC2 instances
  blockinfile:
    path: ~/.ssh/config
    block: |
      Host collab
        HostName {{ hostvars['localhost']['collab_private_ip'] }}
      Host auth
        HostName {{ hostvars['localhost']['auth_private_ip'] }}
      Host matrix
        HostName {{ hostvars['localhost']['matrix_private_ip'] }}
      Host www
        HostName {{ hostvars['localhost']['www_private_ip'] }}

- name: Install requirements for psycopg2
  package:
    name:
      - python-pip
    state: present
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python2

- name: Install psycopg2 for Postgres access
  pip:
    name: psycopg2-binary

- name: Install Postgres client
  shell:
    cmd: amazon-linux-extras install -y {{ amazon_postgres_package }}
    creates: /usr/bin/psql
  become: yes

- name: Create psql service file
  copy:
    dest: "{{ home }}/.pg_service.conf"
    content: |
      [db]
      host={{ hostvars['localhost']['db_host'] }}
      port=5432
      user=postgres
    mode: 0600
  no_log: true

- name: Create HedgeDoc database
  postgresql_db:
    login_host: "{{ hostvars['localhost']['db_host'] }}"
    login_password: "{{ db_root_password }}"
    name: "{{ db_hedgedoc_database }}"

- name: Create HedgeDoc database user
  postgresql_user:
    login_host: "{{ hostvars['localhost']['db_host'] }}"
    login_password: "{{ db_root_password }}"
    db: "{{ db_hedgedoc_database }}"
    name: "{{ db_hedgedoc_username }}"
    password: "{{ db_hedgedoc_password }}"
    priv: "ALL"
    no_password_changes: yes
  no_log: true

- name: Create Keycloak database
  postgresql_db:
    login_host: "{{ hostvars['localhost']['db_host'] }}"
    login_password: "{{ db_root_password }}"
    name: "{{ db_keycloak_database }}"

- name: Create Keycloak database user
  postgresql_user:
    login_host: "{{ hostvars['localhost']['db_host'] }}"
    login_password: "{{ db_root_password }}"
    db: "{{ db_keycloak_database }}"
    name: "{{ db_keycloak_username }}"
    password: "{{ db_keycloak_password }}"
    priv: "ALL"
    no_password_changes: yes
  no_log: true

- name: Create matrix database
  postgresql_db:
    login_host: "{{ hostvars['localhost']['db_host'] }}"
    login_password: "{{ db_root_password }}"
    name: "{{ db_matrix_database }}"
    lc_collate: "C"
    lc_ctype: "C"
    template: "template0"

- name: Create matrix database user
  postgresql_user:
    login_host: "{{ hostvars['localhost']['db_host'] }}"
    login_password: "{{ db_root_password }}"
    db: "{{ db_matrix_database }}"
    name: "{{ db_matrix_username }}"
    password: "{{ db_matrix_password }}"
    priv: "ALL"
    no_password_changes: yes
  no_log: true
