- name: Store terraform variables in file for manual tasks
  copy:
    dest: "{{ playbook_dir }}/secrets/terraform_cluster.{{ terraform_cluster_workspace }}.json"
    content: "{{ terraform_cluster_variables | to_nice_json | regex_replace('\"{', '{') | regex_replace('}\"', '}') | regex_replace('\\\\\"', '\"') }}"

- name: Plan terraform project
  community.general.terraform:
    project_path: "{{ role_path }}/files"
    variables: "{{ terraform_cluster_variables }}"
    state: planned
    plan_file: "{{ terraform_cluster_plan_file }}"
    force_init: yes
    targets: "{{ terraform_cluster_targets }}"
    provider_upgrade: yes
    workspace: "{{ terraform_cluster_workspace }}"
  
  # environment: 
  #   TF_CLOUD_HOSTNAME: "{{ terraform_cluster_backend.hostname }}"
  #   TF_CLOUD_ORGANIZATION: "{{ terraform_cluster_backend.organization }}"
  #   TF_WORKSPACE: "{{ terraform_cluster_workspace }}"
  #   TF_TOKEN_app_terraform_io: "{{ terraform_cluster_backend.token }}"

  register: terraform_result

- name: Print Terraform output
  debug:
    msg: "{{ terraform_result.stdout }}"
