---
nvm_version: "0.38.0"
node_version: "16.4.0"

hedgedoc_version: "1.8.2"
hedgedoc_source: "https://github.com/hedgedoc/hedgedoc/releases/download/{{ hedgedoc_version }}/hedgedoc-{{ hedgedoc_version }}.tar.gz"

hedgedoc_base_path: "~/hedgedoc"
