terraform_cluster_app_config: "{{ terraform_cluster_app_config_default | combine(terraform_cluster_app_config_override, recursive=True) }}"
terraform_cluster_app_config_override:
terraform_cluster_domain:
terraform_cluster_kubeconf_file:
terraform_cluster_stage:
terraform_cluster_helm_release_name: main
terraform_cluster_plan_file: "{{ role_path }}/files/terraform.tfstate.d/{{ terraform_cluster_workspace }}/tfplan"
terraform_cluster_secrets_dir: "{{ playbook_dir }}/secrets"
terraform_cluster_targets: []
terraform_cluster_vault_dir: "{{ playbook_dir }}/vault"
terraform_cluster_workspace: "cluster-{{ terraform_cluster_stage }}"

terraform_cluster_app_config_default:
  backup:
    namespace: backup
    schedule: "0 0 * * *"
    memory: 100Mi

    volume:
      handle:
      size: 10Gi

  buddy:
    namespace: buddy
    memory: 20Mi
    subdomain:
    version: 0.2.0

  cert_manager:
    email:
    hdns_token:
    namespace: cert-manager
    memory: 150Mi
    memory_cainjector: 150Mi
    memory_webhook: 50Mi
    use_production_cert: true
    version_helm: v1.7.1

  collabora:
    admin_password:
    memory: 600Mi
    namespace: collabora
    subdomain:
    version: 21.11.3.6.1
    version_helm: 2.5.1

  element:
    memory: 20Mi
    namespace: element
    version: v1.11.46
    version_helm: 1.3.3
    subdomain:

  grafana:
    admin_password:
    memory: 300Mi
    memory_alertmanager: 50Mi
    memory_loki: 100Mi
    memory_prometheus: 600Mi
    memory_promtail: 100Mi
    namespace: grafana
    subdomain:
    version: 8.4.2
    version_helm: 33.2.1
    version_loki: 2.6.1
    version_loki_helm: 2.8.2

    db:
      database: grafana
      username: grafana
      password:

    keycloak:
      client: grafana
      secret:

    mail:
      account: noreply
      display_name: Grafana
      password:

  hetzner:
    hcloud_token:
    version: v2.5.1

  hedgedoc:
    memory: 300Mi
    namespace: hedgedoc
    secret:
    subdomain:
    version: 1.9.8
    version_helm: 1.1.0

    db:
      database: hedgedoc
      username: hedgedoc
      password:

    keycloak:
      client: hedgedoc
      secret:

    volume:
      handle:
      size: 10Gi

  home:
    memory: 20Mi
    namespace: home
    site_image:
    subdomain:
    version_nginx: 1.23.0
    version_nginx_helm: 13.1.0
    version_nginx_prometheus_exporter: 0.11.0

  jitsi:
    memory_jicofo: 300Mi
    memory_jvb: 1500Mi
    memory_keycloak_adapter: 30Mi
    memory_prosody: 50Mi
    memory_web: 30Mi
    namespace: jitsi
    subdomain:
    version: stable-8960-1
    version_helm: 1.3.7
    version_keycloak_adapter: v20231029
    version_prometheus_exporter: 1.2.1

    keycloak:
      client: jitsi

    secrets:
      jicofo:
      jvb:
      jwt:

  keycloak:
    admin_password:
    mail_from_display_name: Keycloak
    memory: 800Mi
    namespace: keycloak
    realm: primary
    subdomain:
    version: 22.0.4
    version_helm: 2.3.0

    db:
      database: keycloak
      username: keycloak
      password:

    google_identity_provider:
      client_id:
      client_secret:

    mail:
      account: noreply
      display_name: Keycloak
      password:

  mailserver:
    namespace: mailserver
    subdomain:
    version: 11.0.0
    version_helm: 1.0.1

    secrets_files:
      key: "{{ terraform_cluster_secrets_dir }}/mail.{{ terraform_cluster_stage }}.private"
      accounts: "{{ terraform_cluster_secrets_dir }}/postfix-accounts.{{ terraform_cluster_stage }}.cf"
      aliases: "{{ terraform_cluster_secrets_dir }}/postfix-virtual.{{ terraform_cluster_stage }}.cf"

    secrets_files_vault:
      key: "{{ terraform_cluster_vault_dir }}/mail.{{ terraform_cluster_stage }}.private"
      accounts: "{{ terraform_cluster_vault_dir }}/postfix-accounts.{{ terraform_cluster_stage }}.cf"
      aliases: "{{ terraform_cluster_vault_dir }}/postfix-virtual.{{ terraform_cluster_stage }}.cf"

    volume:
      handle:
      size: 10Gi

  minecraft:
    admins:
    memory: 4Gi
    namespace: minecraft
    modpack_url:
    world: world
    rcon_password:
    seed: 0
    subdomain:
    version: latest
    version_game: 1.20.1
    version_helm: 4.9.3

    volume:
      handle:
      size: 10Gi

  minecraft_backup:
    namespace: minecraft

    volume:
      handle:
      size: 50Gi

  nextcloud:
    admin_password:
    memory: 600Mi
    namespace: nextcloud
    subdomain:
    version: 27.1.2-apache
    version_helm: 4.3.3

    db:
      database: nextcloud
      username: nextcloud
      password:

    keycloak:
      client: nextcloud
      secret:

    volume:
      handle:
      size: 10Gi

  postgres:
    memory: 100Mi
    namespace: postgres
    password:
    version: 14.1.0-debian-10-r80

    volume:
      handle:
      size: 10Gi
  
  pretix:
    memory: 1300Mi
    memory_redis: 200Mi
    namespace: pretix
    subdomain:
    version: 4.8.0

    db:
      database: pretix
      username: pretix
      password:

    volume:
      handle:
      size: 10Gi

    mail:
      account: noreply
      display_name: Pretix
      password:

  shlink:
    memory: 100Mi
    memory_web: 20Mi
    namespace: shlink
    subdomain:
    version: 3.2.1
    version_helm: 5.1.2

    db:
      database: shlink
      username: shlink
      password:

  shlink_web:
    memory: 20Mi
    namespace: shlink
    subdomain:
    version: 3.7.2

  sliding_sync:
    memory: 200Mi
    namespace: synapse
    subdomain:
    version: v0.99.11
    version_helm: 0.2.5

    db:
      database: sliding_sync
      username: sliding_sync
      password:

  synapse:
    memory: 600Mi
    memory_sliding_sync: 200Mi
    namespace: synapse
    subdomain:
    version: v1.94.0
    version_helm: 3.7.8

    db:
      database: synapse
      username: synapse
      password:
      params: "LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE template0"

    keycloak:
      client: synapse
      secret:

    secrets:
      registration:
      macaroon:

    volume:
      handle:
      size: 10Gi

terraform_cluster_backend:
  hostname:
  organization:
  token:

terraform_cluster_variables:
  app_config: "{{ terraform_cluster_app_config | to_json }}"
  domain: "{{ terraform_cluster_domain }}"
  kubeconf_file: "{{ terraform_cluster_kubeconf_file }}"
  release_name: "{{ terraform_cluster_helm_release_name }}"
