terraform_cluster_workspace: default

terraform_cluster_kubeconf_file:
terraform_cluster_hcloud_token:

terraform_cluster_plan_file: "{{ role_path }}/files/terraform.tfstate.d/{{ terraform_cluster_workspace }}/tfplan"

terraform_cluster_variables:
  kubeconf_file: "{{ terraform_cluster_kubeconf_file }}"
  hcloud_token: "{{ terraform_cluster_hcloud_token }}"
