terraform_cluster_workspace: default
terraform_cluster_kubeconf_file:
terraform_cluster_hcloud_token:
terraform_cluster_floating_ipv4:
terraform_cluster_domain:
terraform_cluster_subdomains:
  jitsi: jitsi
  jitsi_keycloak: auth
  keycloak: keycloak
  nextcloud: next
  homer: www
  hedgedoc: doc
  element: element
  matrix: matrix
terraform_cluster_use_production_cert: false
terraform_cluster_cert_email:
terraform_cluster_db_passwords:
  keycloak:
terraform_cluster_keycloak_admin_password:
terraform_cluster_jitsi_jwt_secret:
terraform_cluster_keycloak_realm: primary
terraform_cluster_homer_assets_image:
terraform_cluster_project_name:
terraform_cluster_versions:
  jitsi: stable-6726
  jitsi_helm: v1.0.0
  jitsi_keycloak: v0.2.0
  hcloud_csi: v1.6.0
  cert_manager_helm: v1.7.1
  postgres: 14.1.0-debian-10-r80
  keycloak_helm: v17.0.2
  keycloak_theme: v0.3.2
  hedgedoc: 1.9.2
  element: v1.10.4
  nextcloud: v23.0.2
  homer: 22.02.1

terraform_cluster_plan_file: "{{ role_path }}/files/terraform.tfstate.d/{{ terraform_cluster_workspace }}/tfplan"

terraform_cluster_variables:
  kubeconf_file: "{{ terraform_cluster_kubeconf_file }}"
  hcloud_token: "{{ terraform_cluster_hcloud_token }}"
  floating_ipv4: "{{ terraform_cluster_floating_ipv4 }}"
  domain: "{{ terraform_cluster_domain }}"
  subdomains: "{{ terraform_cluster_subdomains | to_json }}"
  use_production_cert: "{{ terraform_cluster_use_production_cert | to_json }}"
  cert_email: "{{ terraform_cluster_cert_email }}"
  versions: "{{ terraform_cluster_versions | to_json }}"
  db_passwords: "{{ terraform_cluster_db_passwords | to_json }}"
  postgres_volume_handle: "{{ terraform_cluster_postgres_volume_handle }}"
  keycloak_admin_password: "{{ terraform_cluster_keycloak_admin_password }}"
  jitsi_jwt_secret: "{{ terraform_cluster_jitsi_jwt_secret }}"
  keycloak_realm: "{{ terraform_cluster_keycloak_realm }}"
  homer_assets_image: "{{ terraform_cluster_homer_assets_image }}"
  project_name: "{{ terraform_cluster_project_name }}"
