terraform_cluster_cert_email:
terraform_cluster_domain:
terraform_cluster_floating_ipv4:
terraform_cluster_google_identity_provider_client_id:
terraform_cluster_google_identity_provider_client_secret:
terraform_cluster_hcloud_token:
terraform_cluster_hedgedoc_secret:
terraform_cluster_home_site_image:
terraform_cluster_kubeconf_file:
terraform_cluster_project_name:
terraform_cluster_workadventure_maps_image:

terraform_cluster_admin_passwords:
  collabora:
  grafana:
  keycloak:
  nextcloud:

terraform_cluster_db_passwords:
  grafana:
  hedgedoc:
  keycloak:
  nextcloud:
  synapse:

terraform_cluster_jitsi_secrets:
  jicofo:
  jvb:
  jwt:

terraform_cluster_keycloak_secrets:
  grafana:
  hedgedoc:
  jitsi:
  nextcloud:

terraform_cluster_synapse_secrets:
  registration:
  macaroon:

terraform_cluster_volume_handles:
  nextcloud:
  postgres:
  synapse:


terraform_cluster_backup_schedule: "0 0 * * *"
terraform_cluster_helm_release_name: primary
terraform_cluster_keycloak_realm: primary
terraform_cluster_plan_file: "{{ role_path }}/files/terraform.tfstate.d/{{ terraform_cluster_workspace }}/tfplan"
terraform_cluster_targets: []
terraform_cluster_use_production_cert: false
terraform_cluster_workadventure_start_map: /src/map.json
terraform_cluster_workspace: default

terraform_cluster_namespaces:
  backup: backup
  cert_manager: cert-manager
  collabora: collabora
  element: element
  grafana: grafana
  hedgedoc: hedgedoc
  hetzner: hetzner
  home: home
  jitsi: jitsi
  keycloak: keycloak
  nextcloud: nextcloud
  postgres: postgres
  synapse: synapse
  workadventure: workadventure

terraform_cluster_resources:
  memory:
    alertmanager: 50Mi
    backup: 100Mi
    canal: 150Mi
    cert_manager: 150Mi
    cert_manager_cainjector: 150Mi
    cert_manager_webhook: 50Mi
    collabora: 600Mi
    element: 20Mi
    grafana: 300Mi
    hedgedoc: 300Mi
    home: 20Mi
    jitsi_jicofo: 300Mi
    jitsi_jvb: 1500Mi
    jitsi_keycloak: 30Mi
    jitsi_web: 30Mi
    keycloak: 800Mi
    loki: 100Mi
    loki_promtail: 100Mi
    nextcloud: 600Mi
    postgres: 100Mi
    prometheus: 600Mi
    prosody: 50Mi
    synapse: 600Mi
    workadventure_front: 20Mi
    workadventure_back: 100Mi
    workadventure_pusher: 100Mi
    workadventure_uploader: 80Mi
    workadventure_maps: 30Mi

terraform_cluster_subdomains:
  collabora: office.next
  element: element
  grafana: grafana
  hedgedoc: doc
  home: www
  jitsi: jitsi
  jitsi_keycloak: auth.jitsi
  keycloak: auth
  nextcloud: next
  synapse: matrix
  workadventure_back: api.play
  workadventure_front: play
  workadventure_maps: maps.play
  workadventure_pusher: pusher.play
  workadventure_uploader: uploader.play

terraform_cluster_versions:
  cert_manager_helm: v1.7.1
  collabora: 21.11.2.4.1
  collabora_helm: 2.2.1
  element: v1.53.0
  element_helm: 2.1.28
  hcloud_csi: v1.6.0
  grafana: 8.4.2
  grafana_helm: 33.2.1
  hedgedoc: 1.9.2
  hedgedoc_helm: 1.1.0
  jitsi: stable-6865
  jitsi_helm: v1.2.1
  jitsi_keycloak: v0.2.0
  jitsi_prometheus_exporter: 1.1.9
  keycloak_helm: v17.0.2
  keycloak_theme: v0.3.2
  loki: v2.4.2
  loki_helm: 2.10.1
  nextcloud: v23.0.2
  nextcloud_helm: 2.12.1
  nginx: 1.21.6
  nginx_helm: 9.9.0
  postgres: 14.1.0-debian-10-r80
  synapse: v1.54.0
  synapse_helm: 2.1.29
  workadventure: v1.8.4
  workadventure_helm: 0.2.0

terraform_cluster_variables:
  admin_passwords: "{{ terraform_cluster_admin_passwords | to_json }}"
  backup_schedule: "{{ terraform_cluster_backup_schedule }}"
  cert_email: "{{ terraform_cluster_cert_email }}"
  db_passwords: "{{ terraform_cluster_db_passwords | to_json }}"
  domain: "{{ terraform_cluster_domain }}"
  floating_ipv4: "{{ terraform_cluster_floating_ipv4 }}"
  google_identity_provider_client_id: "{{ terraform_cluster_google_identity_provider_client_id }}"
  google_identity_provider_client_secret: "{{ terraform_cluster_google_identity_provider_client_secret }}"
  hcloud_token: "{{ terraform_cluster_hcloud_token }}"
  hedgedoc_secret: "{{ terraform_cluster_hedgedoc_secret }}"
  home_site_image: "{{ terraform_cluster_home_site_image }}"
  jitsi_secrets: "{{ terraform_cluster_jitsi_secrets | to_json }}"
  keycloak_realm: "{{ terraform_cluster_keycloak_realm }}"
  keycloak_secrets: "{{ terraform_cluster_keycloak_secrets | to_json }}"
  kubeconf_file: "{{ terraform_cluster_kubeconf_file }}"
  namespaces: "{{ terraform_cluster_namespaces | to_json }}"
  project_name: "{{ terraform_cluster_project_name }}"
  release_name: "{{ terraform_cluster_helm_release_name }}"
  resources: "{{ terraform_cluster_resources | to_json }}"
  subdomains: "{{ terraform_cluster_subdomains | to_json }}"
  synapse_secrets: "{{ terraform_cluster_synapse_secrets | to_json }}"
  use_production_cert: "{{ terraform_cluster_use_production_cert | to_json }}"
  versions: "{{ terraform_cluster_versions | to_json }}"
  volume_handles: "{{ terraform_cluster_volume_handles | to_json }}"
  workadventure_maps_image: "{{ terraform_cluster_workadventure_maps_image }}"
  workadventure_start_map: "{{ terraform_cluster_workadventure_start_map }}"
