terraform_cluster_workspace: default

terraform_cluster_kubeconf_file:
terraform_cluster_hcloud_token:
terraform_cluster_floating_ipv4:
terraform_cluster_domain:
terraform_cluster_subdomains:
  jitsi: jitsi
  keycloak: keycloak
terraform_cluster_use_production_cert: false
terraform_cluster_cert_email:
terraform_cluster_db_root_password:
terraform_cluster_postgres_volume_handle:

terraform_cluster_versions:
  jitsi: stable-6726
  jitsi_helm: v1.0.0
  hcloud_csi: v1.6.0
  cert_manager_helm: v1.7.1
  postgres: 14.1.0-debian-10-r80

terraform_cluster_plan_file: "{{ role_path }}/files/terraform.tfstate.d/{{ terraform_cluster_workspace }}/tfplan"

terraform_cluster_variables:
  kubeconf_file: "{{ terraform_cluster_kubeconf_file }}"
  hcloud_token: "{{ terraform_cluster_hcloud_token }}"
  floating_ipv4: "{{ terraform_cluster_floating_ipv4 }}"
  domain: "{{ terraform_cluster_domain }}"
  subdomains: "{{ terraform_cluster_subdomains | to_json }}"
  use_production_cert: "{{ terraform_cluster_use_production_cert | to_json }}"
  cert_email: "{{ terraform_cluster_cert_email }}"
  versions: "{{ terraform_cluster_versions | to_json }}"
  db_root_password: "{{ terraform_cluster_db_root_password }}"
  postgres_volume_handle: "{{ terraform_cluster_postgres_volume_handle }}"
