---
- name: Copy floating IP network config
  template:
    src: 60-floating-ip.yaml.j2
    dest: /etc/netplan/60-floating-ip.yaml
  notify: Restart networking 
  when: inventory_hostname == 'master'

- meta: flush_handlers

- name: Create Kubelet service config dir
  file:
    path: /etc/systemd/system/kubelet.service.d
    state: directory

- name: Add Hetzner Cloud systemd config
  copy:
    src: 20-hetzner-cloud.conf
    dest: /etc/systemd/system/kubelet.service.d/20-hetzner-cloud.conf
