- name: Destroy terraform project
  community.general.terraform:
    project_path: "{{ role_path }}/files"
    workspace: "{{ terraform_servers_workspace }}"
    variables: "{{ terraform_servers_variables }}"
    state: absent
  register: terraform_result

- name: Print Terraform output
  debug:
    msg: "{{ terraform_result.stdout }}"

- meta: refresh_inventory
