- name: Apply terraform project
  community.general.terraform:
    project_path: "{{ role_path }}/files"
    workspace: "{{ terraform_servers_workspace }}"
    variables: "{{ terraform_servers_variables }}"
    state: present
    plan_file: "{{ terraform_servers_plan_file }}"
  register: terraform_result

- name: Print Terraform output
  debug:
    msg: "{{ terraform_result.stdout }}"

- meta: refresh_inventory

- name: Wait for servers to be reachable
  wait_for:
    host: "{{ item.value.ansible_host }}"
    port: 22
  with_dict: "{{ hostvars }}"
  no_log: true
