# Matrix variables need to override variables defined in group_vars/matrix_servers, so they are put in a smaller scope.

matrix_server_fqn_matrix: "{{ matrix_domain }}"
matrix_server_fqn_element: "{{ element_domain }}"

matrix_ssl_lets_encrypt_support_email: "a@b.com"
matrix_coturn_turn_static_auth_secret: "{{ vault_matrix_coturn_turn_static_auth_secret }}"
matrix_synapse_macaroon_secret_key: "{{ vault_matrix_synapse_macaroon_secret_key }}"

matrix_postgres_enabled: false

matrix_synapse_database_host: "{{ db_host }}"
matrix_synapse_database_user: "{{ db_matrix_username }}"
matrix_synapse_database_password: "{{ db_matrix_password }}"
matrix_synapse_database_database: "{{ db_matrix_database }}"

matrix_ntpd_package: chrony
matrix_ntpd_service: chronyd

matrix_vars_yml_snapshotting_src: "{{ inventory_dir }}/host_vars/matrix/main.yml"
matrix_nginx_proxy_proxy_matrix_client_api_forwarded_location_synapse_oidc_api_enabled: yes
matrix_synapse_password_config_localdb_enabled: false

keycloak_matrix_secret: "{{ vault_keycloak_matrix_secret }}"

matrix_synapse_configuration_extension_yaml: |
  oidc_providers:
  - idp_id: keycloak
    idp_name: "Keycloak"
    issuer: "https://{{ auth_domain }}/auth/realms/{{ keycloak_realm }}"
    client_id: "matrix"
    client_secret: "{{ keycloak_matrix_secret }}"
    scopes: ["openid", "profile"]
    authorization_endpoint: "https://{{ auth_domain }}/auth/realms/{{ keycloak_realm }}/protocol/openid-connect/auth"
    token_endpoint: "https://{{ auth_domain }}/auth/realms/{{ keycloak_realm }}/protocol/openid-connect/token"
    userinfo_endpoint: "https://{{ auth_domain }}/auth/realms/{{ keycloak_realm }}/protocol/openid-connect/userinfo"
    user_mapping_provider:
      config:
        display_name_template: "{% raw %}{{ user.given_name }}{% endraw %} {% raw %}{{ user.family_name }}{% endraw %}"
        email_template: "{% raw %}{{ user.email }}{% endraw %}"
