- name: Set Nextcloud Keycloak config
  kubernetes.core.k8s_exec:
    kubeconfig: "{{ config_kubeconf_file }}"
    namespace: "{{ config_app_config.nextcloud.namespace }}"
    pod: "{{ pods_result.resources[0].metadata.name }}"
    command: su -s /bin/bash -c '/var/www/html/occ user_oidc:provider {{ args }} {{ config_nextcloud_user_oidc.identifier }}' www-data
  vars:
    arg_keys: "{{ ['--'] | product(config_nextcloud_user_oidc.args | dict2items | map(attribute='key')) | map('join') }}"
    arg_values: "{{ config_nextcloud_user_oidc.args | dict2items | map(attribute='value') }}"
    args: "{{ arg_keys | zip(arg_values) | map('join', ' \"') | join('\" ') }}\""
