- name: "Get Nextcloud {{ item.app }} property {{ item.key }}"
  kubernetes.core.k8s_exec:
    kubeconfig: "{{ config_kubeconf_file }}"
    namespace: "{{ config_namespaces.nextcloud }}"
    pod: "{{ pods_result.resources[0].metadata.name }}"
    command: "su -s /bin/bash -c '/var/www/html/occ config:{{ category }}:get {{ identifier }}' www-data"
  register: get_result
  failed_when: get_result.rc != 0 and get_result.stderr | length > 0
  changed_when: false

- name: "Set Nextcloud {{ item.app }} property {{ item.key }}"
  kubernetes.core.k8s_exec:
    kubeconfig: "{{ config_kubeconf_file }}"
    namespace: "{{ config_namespaces.nextcloud }}"
    pod: "{{ pods_result.resources[0].metadata.name }}"
    command: su -s /bin/bash -c '/var/www/html/occ config:{{ category }}:set {{ identifier }} --value "{{ item.value }}" {{ enforce_boolean }}' www-data
  vars:
    enforce_boolean: "{{ '--type=boolean' if item.value is boolean }}"
  # Currently no way to check if the returned value is a string or boolean, so bools are updated always.
  when: get_result.stdout | length == 0 or get_result.stdout[:-1] != item.value
