---
- name: Destroy terraform project
  community.general.terraform:
    project_path: "{{ role_path }}/files"
    workspace: "{{ environment_suffix }}"
    variables:
      project_name: "{{ project_name }}"
      environment_suffix: "{{ environment_suffix }}"
      hcloud_token: "{{ hcloud_token }}"
      ssh_keys: "{{ [ssh_key] | to_json }}"
      domain: "{{ domain }}"
    state: absent
  register: terraform_result

- name: Print Terraform output
  debug:
    msg: "{{ terraform_result.stdout }}"

- meta: refresh_inventory
