---
- name: Apply terraform project
  community.general.terraform:
    project_path: "{{ role_path }}/files"
    workspace: "{{ environment_suffix }}"
    variables: "{{ terraform_variables }}"
    state: present
    plan_file: "{{ role_path }}/files/terraform.tfstate.d/{{ environment_suffix }}/tfplan"
  register: terraform_result

- name: Print Terraform output
  debug:
    msg: "{{ terraform_result.stdout }}"

- meta: refresh_inventory

- name: Wait for servers to be reachable
  wait_for:
    host: "{{ item.value.ansible_host }}"
    port: 22
  with_dict: "{{ hostvars }}"
