---
- name: Plan terraform project
  community.general.terraform:
    project_path: "{{ role_path }}/files"
    workspace: "{{ environment_suffix }}"
    variables: "{{ terraform_variables }}"
    state: planned
    plan_file: "{{ role_path }}/files/terraform.tfstate.d/{{ environment_suffix }}/tfplan"
    force_init: yes
  register: terraform_result

- name: Print Terraform output
  debug:
    msg: "{{ terraform_result.stdout }}"
