all:
  hosts:
    localhost:
      ansible_connection: local
    bastion:
      ansible_host: "{{ bastion_domain }}"

  children:
    gatewayed:
      hosts:
        collab:
          ansible_host: "{{ hostvars['localhost']['collab_private_ip'] }}"
        auth:
          ansible_host: "{{ hostvars['localhost']['auth_private_ip'] }}"
        matrix:
          ansible_host: "{{ hostvars['localhost']['matrix_private_ip'] }}"
        www:
          ansible_host: "{{ hostvars['localhost']['www_private_ip'] }}"
        draw:
          ansible_host: "{{ hostvars['localhost']['draw_private_ip'] }}"
      vars:
        ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q {{ ansible_user }}@{{ bastion_domain }}" -o "StrictHostKeyChecking no"'

    docker_hosts:
      hosts:
        collab:
        auth:
        matrix:
        www:
        draw:

    matrix_servers:
      hosts:
        matrix:
