db_root_password: "{{ vault_db_root_password }}"
ansible_python_interpreter: /usr/bin/python3
ansible_user: ec2-user
home: /home/ec2-user

# ========
# Bastion
# ========
amazon_postgres_package: postgresql13

# ========
# HedgeDoc
# ========
db_hedgedoc_database: "hedgedoc"
db_hedgedoc_username: "hedgedoc"
db_hedgedoc_password: "{{ vault_db_hedgedoc_password }}"
hedgedoc_version: "1.8.2"
hedgedoc_session_secret: "{{ vault_hedgedoc_session_secret }}"

# ========
# Keycloak
# ========
keycloak_version: "14.0.0"
keycloak_password: "{{ vault_keycloak_password }}"
db_keycloak_database: "keycloak"
db_keycloak_username: "keycloak"
db_keycloak_password: "{{ vault_db_keycloak_password }}"
keycloak_hedgedoc_secret: "{{ vault_keycloak_hedgedoc_secret }}"
keycloak_matrix_secret: "{{ vault_keycloak_matrix_secret }}"
keycloak_realm: "kink"
keycloak_realm_api_base: "https://{{ auth_domain }}/auth/admin/realms/{{ keycloak_realm }}"
keycloak_google_client_id: "{{ vault_keycloak_google_client_id }}"
keycloak_google_client_secret: "{{ vault_keycloak_google_client_secret }}"
keycloak_api_headers:
    Content-Type: application/json
    Authorization: "Bearer {{ access_token.json.access_token }}"

# ========
# Matrix
# ========
db_matrix_database: "matrix"
db_matrix_username: "matrix"
db_matrix_password: "{{ vault_db_matrix_password }}"

# ========
# S3
# ========
s3_access_key_id: "{{ vault_s3_access_key_id }}"
s3_access_key_secret: "{{ vault_s3_access_key_secret }}"
