---
- name: Create HedgeDoc dirs
  file:
    path: "{{ home }}/hedgedoc/config/nginx/site-confs"
    state: directory

- name: Copy docker-compose.yml to target machine
  template:
    src: docker-compose.yml.j2
    dest: "{{ home }}/hedgedoc/docker-compose.yml"

- name: Copy SWAG reverse proxy config for HedgeDoc
  template:
    src: hedgedoc.conf.j2
    dest: "{{ home }}/hedgedoc/config/nginx/site-confs/hedgedoc.conf"
  notify: "restart docker"

- name: Run HedgeDoc and reverse proxy
  docker_compose:
    project_src: "{{ home }}/hedgedoc"
  become: yes
