---
- name: Include matrix playbook vars in correct order to simulate in-playbook execution
  include_vars:
    file: "{{ item }}"
  with_items:
    - matrix-docker-ansible-deploy/roles/matrix-base/defaults/main.yml
    - matrix-docker-ansible-deploy/roles/matrix-jitsi/defaults/main.yml
    - matrix-docker-ansible-deploy/group_vars/matrix_servers
    - environments/common/main_matrix.yml
  tags: [ setup-all, setup-matrix-ex ]

- name: Create Prosody plugin dir
  file:
    path: "{{ matrix_jitsi_prosody_plugins_path }}"
    state: directory
  tags: [ setup-all, setup-matrix-ex ]
  become: yes

- name: Copy status Prosody script
  template:
    src: mod_muc_rooms.lua.j2
    dest: "{{ matrix_jitsi_prosody_plugins_path }}/mod_muc_rooms.lua"
  tags: [ setup-all, setup-matrix-ex ]
  become: yes
