---
- name: Copy status Prosody script
  template:
    src: mod_muc_rooms.lua.j2
    dest: "{{ matrix_jitsi_prosody_plugins_path }}/mod_muc_rooms.lua"
  tags: [ setup-all, setup-jitsi-plugins ]
  become: yes
