---
- name: Install pip
  package:
    name:
      - python-pip
    state: present
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python2

- name: Install Docker
  shell:
    cmd: amazon-linux-extras install -y docker
    creates: /usr/bin/docker
  become: yes

- name: Start Docker
  service:
    name: docker
    enabled: yes
    state: started
  become: yes

- name: Install docker-compose
  pip:
    name: docker-compose
  become: yes
