all:
  hosts:
    bastion:
      ansible_host: "{{ bastion_host }}"

  children:
    gatewayed:
      hosts:
        collab:
          ansible_host: "{{ collab_host }}"
        auth:
          ansible_host: "{{ auth_host }}"
      vars:
        ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q {{ ansible_user }}@{{ bastion_host }}"'

    docker_hosts:
      hosts:
        collab:
        auth:
