---
- hosts: localhost
  roles:
    - role: terraform

- hosts: all
  roles:
    - role: update
      tags: 
        - setup-all
        - update

- hosts: all
  roles:
    - role: network
      tags:
        - setup-all
        - setup-network

- hosts: all
  roles:
    - role: tools
      tags:
        - setup-all
        - setup-tools
