---
- hosts: all
  roles:
    - update
  tags: 
    - setup-all
    - update

- hosts: all
  roles:
    - network
  tags:
    - setup-all
    - setup-network

- hosts: all
  roles:
    - docker
  tags:
    - setup-all
    - setup-docker
