---
- hosts: bastion
  roles:
    - db
  tags: [ setup-all, setup-db ]

- hosts: bastion
  roles:
    - ssh_config
  tags: [ setup-all, setup-ssh ]

- hosts: docker_hosts
  roles:
    - docker
  tags: [ setup-all, setup-docker ]

- hosts: collab
  roles:
    - collab

- hosts: auth
  roles:
    - auth

- hosts: matrix
  roles:
    - matrix_ex

- import_playbook: matrix-docker-ansible-deploy/setup.yml
