---
- name: Include matrix playbook vars in correct order to simulate in-playbook execution
  include_vars:
    file: "{{ item }}"
  with_items:
    - matrix-docker-ansible-deploy/roles/matrix-base/defaults/main.yml
    - matrix-docker-ansible-deploy/roles/matrix-jitsi/defaults/main.yml
    - matrix-docker-ansible-deploy/roles/matrix-nginx-proxy/defaults/main.yml
    - matrix-docker-ansible-deploy/group_vars/matrix_servers
    - environments/common/main_matrix.yml
  tags:
    - always

- import_tasks: "{{ role_path }}/tasks/setup_prosody_plugins.yml"
  tags: 
    - setup-all
    - setup-matrix-post
    - setup-prosody-plugins

- import_tasks: "{{ role_path }}/tasks/setup_jitsi_keycloak.yml"
  tags: 
    - setup-all
    - setup-matrix-post
    - setup-jitsi
    - setup-jitsi-keycloak

- import_tasks: "{{ role_path }}/tasks/start.yml"
  tags: 
    - start
    - setup-matrix-post
    - start-jitsi-keycloak
