config_domain:
config_keycloak_realm:
config_kubeconf_file:
config_namespaces_override:
config_subdomains_override:

config_admin_passwords:
  collabora:
  grafana:
  keycloak:
  nextcloud:

config_db_passwords:
  grafana:
  hedgedoc:
  keycloak:
  nextcloud:
  synapse:

config_keycloak_secrets:
  hedgedoc:
  jitsi:
  nextcloud:

config_helm_release_name: primary
config_namespaces: "{{ config_namespaces_default | combine(config_namespaces_override, recursive=True) }}"
config_oidc_url: "https://{{ config_subdomains.keycloak }}.{{ config_domain }}/auth/realms/{{ config_keycloak_realm }}/protocol/openid-connect"
config_release_name: primary
config_subdomains: "{{ config_subdomains_default | combine(config_subdomains_override, recursive=True) }}"

config_nextcloud_config:
  - app: system
    key: overwriteprotocol
    value: https
  - app: system
    key: allow_user_to_change_display_name
    value: "false"
  - app: system
    key: hide_login_form
    value: "true"
  - app: system
    key: skeletondirectory
    value: ""
  - app: system
    index: 2
    key: trusted_domains
    value: "{{ config_subdomains.collabora }}.{{ config_domain }}"
  - app: files
    key: default_quota
    value: "250 MB"
  - app: richdocuments
    key: wopi_url
    value: "https://{{ config_subdomains.collabora }}.{{ config_domain }}"
  - app: richdocuments
    key: public_wopi_url
    value: "https://{{ config_subdomains.collabora }}.{{ config_domain }}"
  - app: richdocuments
    key: disable_certificate_verification
    value: ""
  - app: sociallogin
    key: disable_registration
    value: ""
  - app: sociallogin
    key: create_disabled_users
    value: ""
  - app: sociallogin
    key: allow_login_connect
    value: "1"
  - app: sociallogin
    key: prevent_create_email_exists
    value: ""
  - app: sociallogin
    key: update_profile_on_login
    value: "1"
  - app: sociallogin
    key: no_prune_user_groups
    value: ""
  - app: sociallogin
    key: auto_create_groups
    value: ""
  - app: sociallogin
    key: restrict_users_wo_mapped_groups
    value: ""
  - app: sociallogin
    key: restrict_users_wo_assigned_groups
    value: ""
  - app: sociallogin
    key: disable_notify_admins
    value: ""
  - app: sociallogin
    key: hide_default_login
    value: "1"

config_nextcloud_disable_apps:
  - circles
  - dashboard
  - federation
  - firstrunwizard

config_nextcloud_keycloak_config:
  {
    "custom_oidc": [
      {
        "name": "keycloak",
        "title": "Keycloak",
        "authorizeUrl": "{{ config_oidc_url }}/auth",
        "tokenUrl": "{{ config_oidc_url }}/token",
        "displayNameClaim": "",
        "userInfoUrl": "{{ config_oidc_url }}/userinfo",
        "logoutUrl": "",
        "clientId": "nextcloud",
        "clientSecret": "{{ config_keycloak_secrets.nextcloud }}",
        "scope": "openid",
        "groupsClaim": "groups",
        "style": "keycloak",
        "defaultGroup": "",
        "groupMapping": {
          "admin": "admin"
        }
      }
    ]
  }

config_nextcloud_install_apps:
  - calendar
  - deck
  - richdocuments
  - sociallogin
  - polls

config_namespaces_default:
  backup: backup
  cert_manager: cert-manager
  collabora: collabora
  element: element
  grafana: grafana
  hedgedoc: hedgedoc
  hetzner: hetzner
  home: home
  jitsi: jitsi
  keycloak: keycloak
  nextcloud: nextcloud
  postgres: postgres
  synapse: synapse
  workadventure: workadventure

config_subdomains_default:
  collabora: office.next
  element: element
  grafana: grafana
  hedgedoc: doc
  home: www
  jitsi: jitsi
  jitsi_keycloak: auth.jitsi
  keycloak: auth
  nextcloud: next
  synapse: matrix
  workadventure_back: api.play
  workadventure_front: play
  workadventure_maps: maps.play
  workadventure_pusher: pusher.play
  workadventure_uploader: uploader.play
