config_app_config:
config_domain:
config_kubeconf_file:
config_oidc_url: "https://{{ config_app_config.keycloak.subdomain }}.{{ config_domain }}/realms/{{ config_app_config.keycloak.realm }}/protocol/openid-connect"
config_release_name: main

config_nextcloud_apps_disabled:
  - circles
  - comments
  - contactsinteraction
  - dashboard
  - federation
  - files_pdfviewer
  - files_reminders
  - firstrunwizard
  - nextcloud_announcements
  - notifications
  - password_policy
  - privacy
  - recommendations
  - sharebymail
  - support
  - survey_client
  - systemtags
  - updatenotification
  - user_status
  - weather_status

config_nextcloud_apps_installed:
  - calendar
  - deck
  - richdocuments
  - sociallogin
  - polls
  - forms

config_nextcloud_groups:
  - Default

config_nextcloud_occ:
  system:
    overwriteprotocol: https
    allow_user_to_change_display_name: false
    hide_login_form: false
    skeletondirectory: ""
    profile.enabled: false
    loglevel: 2

    trusted_domains: 
      - localhost
      - "{{ config_app_config.nextcloud.subdomain }}.{{ domain }}"
      - "{{ config_app_config.collabora.subdomain }}.{{ domain }}"
  
  core:
    shareapi_allow_share_dialog_user_enumeration: "no"

  files:
    default_quota: "250 MB"

  richdocuments:
    wopi_url: "https://{{ config_app_config.collabora.subdomain }}.{{ domain }}"
    public_wopi_url: "https://{{ config_app_config.collabora.subdomain }}.{{ domain }}"
    disable_certificate_verification: ""

  sociallogin:
    disable_registration: ""
    create_disabled_users: ""
    allow_login_connect: "1"
    prevent_create_email_exists: ""
    update_profile_on_login: "1"
    no_prune_user_groups: ""
    auto_create_groups: ""
    restrict_users_wo_mapped_groups: ""
    restrict_users_wo_assigned_groups: ""
    disable_notify_admins: ""

  settings:
    profile_enabled_by_default: "0"

  dav:
    calendarSubscriptionRefreshRate: "P1H"

config_nextcloud_oidc_config:
  {
    "custom_oidc": [
      {
        "name": "keycloak",
        "title": "Keycloak",
        "authorizeUrl": "{{ config_oidc_url }}/auth",
        "tokenUrl": "{{ config_oidc_url }}/token",
        "displayNameClaim": "",
        "userInfoUrl": "{{ config_oidc_url }}/userinfo",
        "logoutUrl": "",
        "clientId": "{{ config_app_config.nextcloud.keycloak.client }}",
        "clientSecret": "{{ config_app_config.nextcloud.keycloak.secret }}",
        "scope": "openid",
        "groupsClaim": "groups",
        "style": "keycloak",
        "defaultGroup": "Default",
        "groupMapping": {
          "admin": "admin"
        }
      }
    ]
  }
