config_app_config:
config_domain:
config_kubeconf_file:
config_oidc_url: "https://{{ config_app_config.keycloak.subdomain }}.{{ config_domain }}/realms/{{ config_app_config.keycloak.realm }}/protocol/openid-connect"
config_release_name: main

config_nextcloud_apps_disabled:
  - circles
  - comments
  - contactsinteraction
  - dashboard
  - federation
  - files_pdfviewer
  - files_reminders
  - firstrunwizard
  - nextcloud_announcements
  - notifications
  - password_policy
  - privacy
  - recommendations
  - sharebymail
  - support
  - survey_client
  - systemtags
  - updatenotification
  - user_status
  - weather_status

config_nextcloud_apps_installed:
  - calendar
  - deck
  - richdocuments
  - polls
  - forms
  - user_oidc

config_nextcloud_groups:
  - Default

config_nextcloud_occ:
  system:
    overwriteprotocol: https
    allow_user_to_change_display_name: false
    hide_login_form: false
    skeletondirectory: ""
    profile.enabled: false
    loglevel: 2

    trusted_domains: 
      - localhost
      - "{{ config_app_config.nextcloud.subdomain }}.{{ domain }}"
      - "{{ config_app_config.collabora.subdomain }}.{{ domain }}"
  
  core:
    shareapi_allow_share_dialog_user_enumeration: "no"

  files:
    default_quota: "250 MB"

  richdocuments:
    wopi_url: "https://{{ config_app_config.collabora.subdomain }}.{{ domain }}"
    public_wopi_url: "https://{{ config_app_config.collabora.subdomain }}.{{ domain }}"
    disable_certificate_verification: ""

  user_oidc:
    allow_multiple_user_backends: "0"

  settings:
    profile_enabled_by_default: "0"

  dav:
    calendarSubscriptionRefreshRate: "P1H"

config_nextcloud_user_oidc:
  identifier: "{{ config_app_config.nextcloud.keycloak.name }}"

  args:
    clientid: "{{ config_app_config.nextcloud.keycloak.client }}"
    clientsecret: "{{ config_app_config.nextcloud.keycloak.secret }}"
    discoveryuri: "https://{{ config_app_config.keycloak.subdomain }}.{{ config_domain }}/realms/{{ config_app_config.keycloak.realm }}/.well-known/openid-configuration"
    scope: openid email private_profile
    unique-uid: 0
    check-bearer: 0
    send-id-token-hint: 1
    mapping-display-name: preferred_username
    mapping-email: email
    mapping-quota: ""
    mapping-uid: sub
    extra-claims: ""
